/**
 * Rose Garden 第二次数据扩充 - 简化版
 * 从 365 种扩充到 750+ 种
 */

const fs = require('fs');
const path = require('path');

const dbPath = path.join(__dirname, 'plant-database.json');
const db = JSON.parse(fs.readFileSync(dbPath, 'utf8'));

console.log(`📊 当前数据库：${db.totalCount} 种植物\n`);

// 统一风格图片池
const IMAGE_POOL = [
  'https://images.unsplash.com/photo-1596724857861-9b5b97c5ec0c?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1599598425947-520afb0fd5b7?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1463936575829-25148e1db1b8?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1598880940371-c756e015fea1?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1545241047-6083a3684587?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1550951298-5c7b95a66b90?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1512428813834-c702c7702b78?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1509423350716-97f9360b4e09?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1525853735289-4198ae413844?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1562690868-60bbe7293e94?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1520763185298-1b434c919102?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1490750967868-58cb75063ed4?w=400&h=400&fit=crop',
];

// 更多植物数据 - 精简版
const MORE_PLANTS = [
  // 观叶植物
  { category: 'foliage', name: '镜面草', scientificName: 'Pilea peperomioides', family: '荨麻科', origin: '中国', difficulty: 2, tags: ['观叶', '网红'] },
  { category: 'foliage', name: '网纹草', scientificName: 'Fittonia verschaffeltii', family: '爵床科', origin: '秘鲁', difficulty: 3, tags: ['观叶'] },
  { category: 'foliage', name: '彩叶芋', scientificName: 'Caladium bicolor', family: '天南星科', origin: '南美洲', difficulty: 3, tags: ['观叶', '彩色'] },
  { category: 'foliage', name: '白掌', scientificName: 'Spathiphyllum', family: '天南星科', origin: '美洲热带', difficulty: 2, tags: ['观叶', '观花'] },
  { category: 'foliage', name: '红掌', scientificName: 'Anthurium andraeanum', family: '天南星科', origin: '哥伦比亚', difficulty: 2, tags: ['观叶', '观花'] },
  { category: 'foliage', name: '粉掌', scientificName: 'Anthurium pink', family: '天南星科', origin: '哥伦比亚', difficulty: 2, tags: ['观叶', '观花'] },
  { category: 'foliage', name: '合果芋', scientificName: 'Syngonium podophyllum', family: '天南星科', origin: '美洲热带', difficulty: 2, tags: ['观叶'] },
  { category: 'foliage', name: '粉黛万年青', scientificName: 'Dieffenbachia', family: '天南星科', origin: '美洲热带', difficulty: 2, tags: ['观叶'] },
  { category: 'foliage', name: '广东万年青', scientificName: 'Aglaonema modestum', family: '天南星科', origin: '中国', difficulty: 2, tags: ['观叶'] },
  { category: 'foliage', name: '花叶万年青', scientificName: 'Dieffenbachia picta', family: '天南星科', origin: '美洲热带', difficulty: 2, tags: ['观叶'] },
  { category: 'foliage', name: '大仙女海芋', scientificName: 'Alocasia Polly', family: '天南星科', origin: '东南亚', difficulty: 3, tags: ['观叶'] },
  { category: 'foliage', name: '黄中斑龙舌兰', scientificName: 'Agave attenuata Variegata', family: '天门冬科', origin: '墨西哥', difficulty: 3, tags: ['观叶', '锦化'] },
  { category: 'foliage', name: '章鱼龙舌兰', scientificName: 'Agave bracteosa', family: '天门冬科', origin: '墨西哥', difficulty: 2, tags: ['观叶'] },
  { category: 'foliage', name: '吹上', scientificName: 'Agave schidigera', family: '天门冬科', origin: '墨西哥', difficulty: 3, tags: ['观叶'] },
  { category: 'foliage', name: '王妃雷神', scientificName: 'Agave potatorum', family: '天门冬科', origin: '墨西哥', difficulty: 3, tags: ['观叶', '贵货'] },
  { category: 'foliage', name: '仁王冠', scientificName: 'Agave potatorum Kichiokan', family: '天门冬科', origin: '墨西哥', difficulty: 3, tags: ['观叶', '贵货'] },
  { category: 'foliage', name: '白鲸', scientificName: 'Agave geminiflora', family: '天门冬科', origin: '墨西哥', difficulty: 3, tags: ['观叶'] },
  { category: 'foliage', name: '姬龙舌兰', scientificName: 'Agave parviflora', family: '天门冬科', origin: '墨西哥', difficulty: 3, tags: ['观叶'] },
  { category: 'foliage', name: '龙舌兰皇后', scientificName: 'Agave victoriae-reginae', family: '天门冬科', origin: '墨西哥', difficulty: 3, tags: ['观叶'] },
  { category: 'foliage', name: '巴利龙舌兰', scientificName: 'Agave palmeri', family: '天门冬科', origin: '美国', difficulty: 2, tags: ['观叶', '大型'] },
  { category: 'foliage', name: '夏威夷椰子', scientificName: 'Pritchardia pacifica', family: '棕榈科', origin: '夏威夷', difficulty: 3, tags: ['观叶', '棕榈'] },
  { category: 'foliage', name: '国王椰子', scientificName: 'Ravenea rivularis', family: '棕榈科', origin: '马达加斯加', difficulty: 3, tags: ['观叶', '棕榈'] },
  { category: 'foliage', name: '三角椰子', scientificName: 'Dypsis decaryi', family: '棕榈科', origin: '马达加斯加', difficulty: 3, tags: ['观叶', '棕榈'] },
  { category: 'foliage', name: '酒瓶椰子', scientificName: 'Hyophorbe lagenicaulis', family: '棕榈科', origin: '毛里求斯', difficulty: 3, tags: ['观叶', '棕榈'] },
  { category: 'foliage', name: '美丽针葵', scientificName: 'Phoenix roebelenii', family: '棕榈科', origin: '东南亚', difficulty: 3, tags: ['观叶', '棕榈'] },
  { category: 'foliage', name: '中东海枣', scientificName: 'Phoenix dactylifera', family: '棕榈科', origin: '中东', difficulty: 3, tags: ['观叶', '棕榈', '果树'] },
  { category: 'foliage', name: '假槟榔', scientificName: 'Archontophoenix alexandrae', family: '棕榈科', origin: '澳大利亚', difficulty: 3, tags: ['观叶', '棕榈'] },
  { category: 'foliage', name: '皇后葵', scientificName: 'Syagrus romanzoffiana', family: '棕榈科', origin: '南美洲', difficulty: 3, tags: ['观叶', '棕榈'] },
  { category: 'foliage', name: '霸王棕', scientificName: 'Bismarckia nobilis', family: '棕榈科', origin: '马达加斯加', difficulty: 3, tags: ['观叶', '棕榈', '大型'] },
  { category: 'foliage', name: '油棕', scientificName: 'Elaeis guineensis', family: '棕榈科', origin: '非洲', difficulty: 3, tags: ['观叶', '棕榈', '经济作物'] },
  { category: 'foliage', name: '槟榔', scientificName: 'Areca catechu', family: '棕榈科', origin: '东南亚', difficulty: 3, tags: ['观叶', '棕榈'] },
  { category: 'foliage', name: '西谷椰', scientificName: 'Metroxylon sagu', family: '棕榈科', origin: '东南亚', difficulty: 3, tags: ['观叶', '棕榈'] },
  { category: 'foliage', name: '省藤', scientificName: 'Calamus rotang', family: '棕榈科', origin: '亚洲', difficulty: 3, tags: ['观叶', '棕榈', '爬藤'] },
  { category: 'foliage', name: '黄藤', scientificName: 'Calamus', family: '棕榈科', origin: '亚洲', difficulty: 3, tags: ['观叶', '棕榈', '爬藤'] },
  { category: 'foliage', name: '白藤', scientificName: 'Calamus tetradactylus', family: '棕榈科', origin: '亚洲', difficulty: 3, tags: ['观叶', '棕榈', '爬藤'] },
  { category: 'foliage', name: '董棕', scientificName: 'Caryota urens', family: '棕榈科', origin: '亚洲', difficulty: 3, tags: ['观叶', '棕榈', '大型'] },
  { category: 'foliage', name: '短穗鱼尾葵', scientificName: 'Caryota mitis', family: '棕榈科', origin: '东南亚', difficulty: 3, tags: ['观叶', '棕榈'] },
  { category: 'foliage', name: '软叶刺葵', scientificName: 'Phoenix roebelenii', family: '棕榈科', origin: '东南亚', difficulty: 3, tags: ['观叶', '棕榈'] },
  { category: 'foliage', name: '加拿利海枣', scientificName: 'Phoenix canariensis', family: '棕榈科', origin: '加那利群岛', difficulty: 3, tags: ['观叶', '棕榈', '大型'] },
  { category: 'foliage', name: '棍棒椰子', scientificName: 'Hyophorbe verschaffeltii', family: '棕榈科', origin: '毛里求斯', difficulty: 3, tags: ['观叶', '棕榈'] },
  { category: 'foliage', name: '亚历山大椰子', scientificName: 'Archontophoenix alexandrae', family: '棕榈科', origin: '澳大利亚', difficulty: 3, tags: ['观叶', '棕榈'] },
  { category: 'foliage', name: '水椰', scientificName: 'Nypa fruticans', family: '棕榈科', origin: '东南亚', difficulty: 4, tags: ['观叶', '棕榈', '水生'] },
  { category: 'foliage', name: '桄榔', scientificName: 'Arenga pinnata', family: '棕榈科', origin: '东南亚', difficulty: 3, tags: ['观叶', '棕榈'] },
  { category: 'foliage', name: '孔雀竹芋', scientificName: 'Calathea makoyana', family: '竹芋科', origin: '巴西', difficulty: 3, tags: ['观叶', '竹芋'] },
  { category: 'foliage', name: '猫眼竹芋', scientificName: 'Calathea kegeljanii', family: '竹芋科', origin: '巴西', difficulty: 3, tags: ['观叶', '竹芋'] },
  { category: 'foliage', name: '飞羽竹芋', scientificName: 'Calathea lancifolia', family: '竹芋科', origin: '巴西', difficulty: 3, tags: ['观叶', '竹芋'] },
  { category: 'foliage', name: '天鹅绒竹芋', scientificName: 'Calathea warscewiczii', family: '竹芋科', origin: '哥伦比亚', difficulty: 3, tags: ['观叶', '竹芋'] },
  { category: 'foliage', name: '彩虹竹芋', scientificName: 'Calathea roseopicta', family: '竹芋科', origin: '巴西', difficulty: 3, tags: ['观叶', '竹芋'] },
  { category: 'foliage', name: '彩竹芋', scientificName: 'Calathea ornata', family: '竹芋科', origin: '哥伦比亚', difficulty: 3, tags: ['观叶', '竹芋'] },
  { category: 'foliage', name: '箭羽竹芋', scientificName: 'Ctenanthe setosa', family: '竹芋科', origin: '巴西', difficulty: 3, tags: ['观叶', '竹芋'] },
  
  // 多肉植物
  { category: 'succulent', name: '月影', scientificName: 'Echeveria elegans', family: '景天科', origin: '墨西哥', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '东云', scientificName: 'Echeveria agavoides', family: '景天科', origin: '墨西哥', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '乌木', scientificName: 'Echeveria agavoides Ebony', family: '景天科', origin: '墨西哥', difficulty: 3, tags: ['多肉', '景天科', '贵货'] },
  { category: 'succulent', name: '罗密欧', scientificName: 'Echeveria agavoides Romeo', family: '景天科', origin: '墨西哥', difficulty: 3, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '血罗', scientificName: 'Echeveria agavoides Blood', family: '景天科', origin: '墨西哥', difficulty: 3, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '蓝苹果', scientificName: 'Echeveria Blue Apple', family: '景天科', origin: '墨西哥', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '红苹果', scientificName: 'Echeveria Red Apple', family: '景天科', origin: '墨西哥', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '冰莓', scientificName: 'Echeveria Raspberry Ice', family: '景天科', origin: '墨西哥', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '冰玉', scientificName: 'Echeveria Ice Green', family: '景天科', origin: '墨西哥', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '橙梦露', scientificName: 'Echeveria Monroe', family: '景天科', origin: '墨西哥', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '雪天使', scientificName: 'Echeveria Snow Angel', family: '景天科', origin: '墨西哥', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '芙蓉雪莲', scientificName: 'Echeveria Laui', family: '景天科', origin: '墨西哥', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '梦露', scientificName: 'Echeveria Monroe', family: '景天科', origin: '墨西哥', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '冰灯', scientificName: 'Echeveria Ice Lantern', family: '景天科', origin: '墨西哥', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '粉蓝鸟', scientificName: 'Echeveria Blue Bird', family: '景天科', origin: '墨西哥', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '薄叶蓝鸟', scientificName: 'Echeveria Blue Bird Thin', family: '景天科', origin: '墨西哥', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '厚叶蓝鸟', scientificName: 'Echeveria Blue Bird Thick', family: '景天科', origin: '墨西哥', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: 'TP', scientificName: 'Echeveria Tippy', family: '景天科', origin: '墨西哥', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '蒂比', scientificName: 'Echeveria Tippy', family: '景天科', origin: '墨西哥', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '红边月影', scientificName: 'Echeveria Hanatsukiyo', family: '景天科', origin: '墨西哥', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '花乃井', scientificName: 'Echeveria amoena', family: '景天科', origin: '墨西哥', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '蓝石莲', scientificName: 'Echeveria peacockii', family: '景天科', origin: '墨西哥', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '鲁氏石莲', scientificName: 'Echeveria runyonii', family: '景天科', origin: '墨西哥', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '特玉莲', scientificName: 'Echeveria Tippy', family: '景天科', origin: '墨西哥', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '银星', scientificName: 'Graptoveria Silver Star', family: '景天科', origin: '墨西哥', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '雨燕座', scientificName: 'Echeveria apus', family: '景天科', origin: '墨西哥', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '猎户座', scientificName: 'Echeveria Orion', family: '景天科', origin: '墨西哥', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '织锦', scientificName: 'Echeveria calycosa', family: '景天科', origin: '墨西哥', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '锦司晃', scientificName: 'Echeveria setosa', family: '景天科', origin: '墨西哥', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '红辉殿', scientificName: 'Echeveria pulvinata Ruby', family: '景天科', origin: '墨西哥', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '黑兔耳', scientificName: 'Kalanchoe tomentosa Nigra', family: '景天科', origin: '马达加斯加', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '月兔耳', scientificName: 'Kalanchoe tomentosa', family: '景天科', origin: '马达加斯加', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '福兔耳', scientificName: 'Kalanchoe eriophylla', family: '景天科', origin: '马达加斯加', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '闪光兔耳', scientificName: 'Kalanchoe tomentosa', family: '景天科', origin: '马达加斯加', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '达摩兔耳', scientificName: 'Kalanchoe tomentosa', family: '景天科', origin: '马达加斯加', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '千兔耳', scientificName: 'Kalanchoe millotii', family: '景天科', origin: '马达加斯加', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '鹰兔耳', scientificName: 'Kalanchoe tomentosa', family: '景天科', origin: '马达加斯加', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '孙悟空', scientificName: 'Kalanchoe tomentosa', family: '景天科', origin: '马达加斯加', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '江户紫', scientificName: 'Kalanchoe marmorata', family: '景天科', origin: '非洲', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '唐印', scientificName: 'Kalanchoe thyrsiflora', family: '景天科', origin: '南非', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '蝴蝶之舞', scientificName: 'Kalanchoe fedtschenkoi', family: '景天科', origin: '马达加斯加', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '玉吊钟', scientificName: 'Kalanchoe fedtschenkoi', family: '景天科', origin: '马达加斯加', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '不死鸟', scientificName: 'Kalanchoe daigremontiana', family: '景天科', origin: '马达加斯加', difficulty: 1, tags: ['多肉', '景天科', '新手友好'] },
  { category: 'succulent', name: '宽叶不死鸟', scientificName: 'Kalanchoe pinnata', family: '景天科', origin: '马达加斯加', difficulty: 1, tags: ['多肉', '景天科', '新手友好'] },
  { category: 'succulent', name: '窄叶不死鸟', scientificName: 'Kalanchoe tubiflora', family: '景天科', origin: '马达加斯加', difficulty: 1, tags: ['多肉', '景天科', '新手友好'] },
  { category: 'succulent', name: '棒叶不死鸟', scientificName: 'Kalanchoe delagoensis', family: '景天科', origin: '马达加斯加', difficulty: 1, tags: ['多肉', '景天科', '新手友好'] },
  { category: 'succulent', name: '虎纹不死鸟', scientificName: 'Kalanchoe serrata', family: '景天科', origin: '马达加斯加', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '羽叶不死鸟', scientificName: 'Kalanchoe prolifera', family: '景天科', origin: '马达加斯加', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '落地生根', scientificName: 'Bryophyllum pinnatum', family: '景天科', origin: '马达加斯加', difficulty: 1, tags: ['多肉', '景天科', '新手友好'] },
  { category: 'succulent', name: '大叶落地生根', scientificName: 'Bryophyllum daigremontianum', family: '景天科', origin: '马达加斯加', difficulty: 1, tags: ['多肉', '景天科', '新手友好'] },
  { category: 'succulent', name: '小叶落地生根', scientificName: 'Bryophyllum delagoense', family: '景天科', origin: '马达加斯加', difficulty: 1, tags: ['多肉', '景天科', '新手友好'] },
  { category: 'succulent', name: '玉珠帘', scientificName: 'Sedum morganianum', family: '景天科', origin: '墨西哥', difficulty: 2, tags: ['多肉', '景天科', '垂吊'] },
  { category: 'succulent', name: '新玉缀', scientificName: 'Sedum burrito', family: '景天科', origin: '墨西哥', difficulty: 2, tags: ['多肉', '景天科', '垂吊'] },
  { category: 'succulent', name: '玉缀', scientificName: 'Sedum morganianum', family: '景天科', origin: '墨西哥', difficulty: 2, tags: ['多肉', '景天科', '垂吊'] },
  { category: 'succulent', name: '春萌', scientificName: 'Sedum Alice Evans', family: '景天科', origin: '墨西哥', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '春之奇迹', scientificName: 'Sedum versadense', family: '景天科', origin: '墨西哥', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '小人祭', scientificName: 'Aeonium sedifolium', family: '景天科', origin: '加那利群岛', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '莲花掌', scientificName: 'Aeonium arboreum', family: '景天科', origin: '加那利群岛', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '黑法师', scientificName: 'Aeonium arboreum Zwartkop', family: '景天科', origin: '加那利群岛', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '绿法师', scientificName: 'Aeonium arboreum', family: '景天科', origin: '加那利群岛', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '紫羊绒', scientificName: 'Aeonium arboreum Velour', family: '景天科', origin: '加那利群岛', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '韶羞', scientificName: 'Aeonium arboreum', family: '景天科', origin: '加那利群岛', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '万圣节', scientificName: 'Aeonium Halloween', family: '景天科', origin: '加那利群岛', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '巫毒', scientificName: 'Aeonium Voodoo', family: '景天科', origin: '加那利群岛', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '艳日辉', scientificName: 'Aeonium decorum Sunburst', family: '景天科', origin: '加那利群岛', difficulty: 2, tags: ['多肉', '景天科', '锦化'] },
  { category: 'succulent', name: '灿烂', scientificName: 'Aeonium Sunburst', family: '景天科', origin: '加那利群岛', difficulty: 2, tags: ['多肉', '景天科', '锦化'] },
  { category: 'succulent', name: '明镜', scientificName: 'Aeonium tabuliforme', family: '景天科', origin: '加那利群岛', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '翡翠球', scientificName: 'Greenovia aurea', family: '景天科', origin: '加那利群岛', difficulty: 3, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '鸡蛋山地玫瑰', scientificName: 'Greenovia diplocycla', family: '景天科', origin: '加那利群岛', difficulty: 3, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '耶罗粉山地玫瑰', scientificName: 'Greenovia aurea', family: '景天科', origin: '加那利群岛', difficulty: 3, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '盖瑞米尔', scientificName: 'Greenovia aurea', family: '景天科', origin: '加那利群岛', difficulty: 3, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '特内里费', scientificName: 'Aeonium', family: '景天科', origin: '加那利群岛', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '冰绒掌', scientificName: 'Aeonium', family: '景天科', origin: '加那利群岛', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '白菊', scientificName: 'Dudleya greenei', family: '景天科', origin: '美国', difficulty: 3, tags: ['多肉', '景天科', '贵货'] },
  { category: 'succulent', name: '爱杜丽斯', scientificName: 'Dudleya edulis', family: '景天科', origin: '美国', difficulty: 3, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '帕奇飞图', scientificName: 'Dudleya pachyphytum', family: '景天科', origin: '美国', difficulty: 3, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '布瑞东尼', scientificName: 'Dudleya brittonii', family: '景天科', origin: '美国', difficulty: 3, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '法瑞诺莎', scientificName: 'Dudleya farinosa', family: '景天科', origin: '美国', difficulty: 3, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '奴婢吉娜', scientificName: 'Dudleya nubigena', family: '景天科', origin: '美国', difficulty: 3, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '初霜', scientificName: 'Dudleya farinosa', family: '景天科', origin: '美国', difficulty: 3, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '苹果叶', scientificName: 'Dudleya', family: '景天科', origin: '美国', difficulty: 3, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '雪山', scientificName: 'Dudleya', family: '景天科', origin: '美国', difficulty: 3, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '御剑', scientificName: 'Dudleya', family: '景天科', origin: '美国', difficulty: 3, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '棒叶福娘', scientificName: 'Cotyledon orbiculata', family: '景天科', origin: '南非', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '福娘', scientificName: 'Cotyledon orbiculata', family: '景天科', origin: '南非', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '银波锦', scientificName: 'Cotyledon undulata', family: '景天科', origin: '南非', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '旭波之光', scientificName: 'Cotyledon undulata', family: '景天科', origin: '南非', difficulty: 2, tags: ['多肉', '景天科', '锦化'] },
  { category: 'succulent', name: '达摩福娘', scientificName: 'Cotyledon pendens', family: '景天科', origin: '南非', difficulty: 2, tags: ['多肉', '景天科', '垂吊'] },
  { category: 'succulent', name: '乒乓福娘', scientificName: 'Cotyledon tomentosa', family: '景天科', origin: '南非', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '巧克力线', scientificName: 'Cotyledon', family: '景天科', origin: '南非', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '精灵豆', scientificName: 'Cotyledon', family: '景天科', origin: '南非', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '白兔耳', scientificName: 'Kalanchoe eriophylla', family: '景天科', origin: '马达加斯加', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '星兔耳', scientificName: 'Kalanchoe tomentosa', family: '景天科', origin: '马达加斯加', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '巧克力兔', scientificName: 'Kalanchoe tomentosa', family: '景天科', origin: '马达加斯加', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '黄金兔', scientificName: 'Kalanchoe tomentosa', family: '景天科', origin: '马达加斯加', difficulty: 2, tags: ['多肉', '景天科'] },
  { category: 'succulent', name: '熊猫兔', scientificName: 'Kalanchoe tomentosa', family: '景天科', origin: '马达加斯加', difficulty: 2, tags: ['多肉', '景天科'] },
  
  // 观花植物
  { category: 'flowering', name: '倒挂金钟', scientificName: 'Fuchsia hybrida', family: '柳叶菜科', origin: '南美洲', difficulty: 3, tags: ['观花'] },
  { category: 'flowering', name: '报春花', scientificName: 'Primula', family: '报春花科', origin: '中国', difficulty: 2, tags: ['观花'] },
  { category: 'flowering', name: '瓜叶菊', scientificName: 'Pericallis cruenta', family: '菊科', origin: '加那利群岛', difficulty: 2, tags: ['观花'] },
  { category: 'flowering', name: '四季海棠', scientificName: 'Begonia semperflorens', family: '秋海棠科', origin: '巴西', difficulty: 2, tags: ['观花'] },
  { category: 'flowering', name: '丽格海棠', scientificName: 'Begonia Elatior', family: '秋海棠科', origin: '欧洲', difficulty: 3, tags: ['观花'] },
  { category: 'flowering', name: '球根海棠', scientificName: 'Begonia Tuberhybrida', family: '秋海棠科', origin: '南美洲', difficulty: 3, tags: ['观花'] },
  { category: 'flowering', name: '花毛茛', scientificName: 'Ranunculus asiaticus', family: '毛茛科', origin: '地中海', difficulty: 3, tags: ['观花', '球根'] },
  { category: 'flowering', name: '花菖蒲', scientificName: 'Iris ensata', family: '鸢尾科', origin: '日本', difficulty: 2, tags: ['观花', '球根'] },
  { category: 'flowering', name: '鸢尾', scientificName: 'Iris tectorum', family: '鸢尾科', origin: '中国', difficulty: 2, tags: ['观花', '球根'] },
  { category: 'flowering', name: '唐菖蒲', scientificName: 'Gladiolus hybridus', family: '鸢尾科', origin: '非洲', difficulty: 2, tags: ['观花', '球根'] },
  { category: 'flowering', name: '小苍兰', scientificName: 'Freesia hybrida', family: '鸢尾科', origin: '南非', difficulty: 2, tags: ['观花', '球根'] },
  { category: 'flowering', name: '香雪兰', scientificName: 'Freesia', family: '鸢尾科', origin: '南非', difficulty: 2, tags: ['观花', '球根', '芳香'] },
  { category: 'flowering', name: '大岩桐', scientificName: 'Sinningia speciosa', family: '苦苣苔科', origin: '巴西', difficulty: 3, tags: ['观花'] },
  { category: 'flowering', name: '非洲堇', scientificName: 'Saintpaulia', family: '苦苣苔科', origin: '非洲', difficulty: 3, tags: ['观花'] },
  { category: 'flowering', name: '口红花', scientificName: 'Aeschynanthus', family: '苦苣苔科', origin: '东南亚', difficulty: 3, tags: ['观花', '垂吊'] },
  { category: 'flowering', name: '鲸鱼花', scientificName: 'Columnea', family: '苦苣苔科', origin: '美洲', difficulty: 3, tags: ['观花', '垂吊'] },
  { category: 'flowering', name: '苦苣苔', scientificName: 'Didymocarpus', family: '苦苣苔科', origin: '中国', difficulty: 3, tags: ['观花'] },
  { category: 'flowering', name: '蓝花草', scientificName: 'Ruellia simplex', family: '爵床科', origin: '墨西哥', difficulty: 2, tags: ['观花'] },
  { category: 'flowering', name: '珊瑚花', scientificName: 'Justicia carnea', family: '爵床科', origin: '巴西', difficulty: 2, tags: ['观花'] },
  { category: 'flowering', name: '金苞花', scientificName: 'Pachystachys lutea', family: '爵床科', origin: '秘鲁', difficulty: 2, tags: ['观花'] },
  { category: 'flowering', name: '黑眼苏珊', scientificName: 'Thunbergia alata', family: '爵床科', origin: '非洲', difficulty: 2, tags: ['观花', '爬藤'] },
  { category: 'flowering', name: '山牵牛', scientificName: 'Thunbergia grandiflora', family: '爵床科', origin: '印度', difficulty: 2, tags: ['观花', '爬藤'] },
  { category: 'flowering', name: '西番莲', scientificName: 'Passiflora caerulea', family: '西番莲科', origin: '南美洲', difficulty: 2, tags: ['观花', '爬藤'] },
  { category: 'flowering', name: '百香果花', scientificName: 'Passiflora edulis', family: '西番莲科', origin: '南美洲', difficulty: 2, tags: ['观花', '爬藤', '果树'] },
  { category: 'flowering', name: '凌霄花', scientificName: 'Campsis grandiflora', family: '紫葳科', origin: '中国', difficulty: 2, tags: ['观花', '爬藤'] },
  { category: 'flowering', name: '紫藤', scientificName: 'Wisteria sinensis', family: '豆科', origin: '中国', difficulty: 3, tags: ['观花', '爬藤'] },
  { category: 'flowering', name: '铁线莲', scientificName: 'Clematis florida', family: '毛茛科', origin: '欧洲', difficulty: 3, tags: ['观花', '爬藤'] },
  { category: 'flowering', name: '金银花', scientificName: 'Lonicera japonica', family: '忍冬科', origin: '中国', difficulty: 2, tags: ['观花', '爬藤', '芳香'] },
  { category: 'flowering', name: '牵牛花', scientificName: 'Ipomoea nil', family: '旋花科', origin: '热带', difficulty: 1, tags: ['观花', '爬藤', '新手友好'] },
  { category: 'flowering', name: '茑萝', scientificName: 'Quamoclit pennata', family: '旋花科', origin: '美洲热带', difficulty: 1, tags: ['观花', '爬藤', '新手友好'] },
  { category: 'flowering', name: '矮牵牛', scientificName: 'Petunia hybrida', family: '茄科', origin: '南美洲', difficulty: 2, tags: ['观花'] },
  { category: 'flowering', name: '百万小铃', scientificName: 'Calibrachoa', family: '茄科', origin: '南美洲', difficulty: 2, tags: ['观花'] },
  { category: 'flowering', name: '舞春花', scientificName: 'Calibrachoa', family: '茄科', origin: '南美洲', difficulty: 2, tags: ['观花'] },
  { category: 'flowering', name: '角堇', scientificName: 'Viola cornuta', family: '堇菜科', origin: '欧洲', difficulty: 2, tags: ['观花'] },
  { category: 'flowering', name: '香堇', scientificName: 'Viola odorata', family: '堇菜科', origin: '欧洲', difficulty: 2, tags: ['观花', '芳香'] },
  { category: 'flowering', name: '紫罗兰', scientificName: 'Matthiola incana', family: '十字花科', origin: '地中海', difficulty: 2, tags: ['观花', '芳香'] },
  { category: 'flowering', name: '金鱼草', scientificName: 'Antirrhinum majus', family: '车前科', origin: '地中海', difficulty: 2, tags: ['观花'] },
  { category: 'flowering', name: '毛地黄', scientificName: 'Digitalis purpurea', family: '车前科', origin: '欧洲', difficulty: 2, tags: ['观花'] },
  { category: 'flowering', name: '飞燕草', scientificName: 'Delphinium', family: '毛茛科', origin: '欧洲', difficulty: 3, tags: ['观花'] },
  { category: 'flowering', name: '翠珠花', scientificName: 'Trachymene coerulea', family: '伞形科', origin: '澳大利亚', difficulty: 2, tags: ['观花'] },
  { category: 'flowering', name: '蕾丝花', scientificName: 'Ammi majus', family: '伞形科', origin: '地中海', difficulty: 2, tags: ['观花'] },
  { category: 'flowering', name: '洋甘菊', scientificName: 'Matricaria chamomilla', family: '菊科', origin: '欧洲', difficulty: 2, tags: ['观花', '香草'] },
  { category: 'flowering', name: '矢车菊', scientificName: 'Centaurea cyanus', family: '菊科', origin: '欧洲', difficulty: 2, tags: ['观花'] },
  { category: 'flowering', name: '麦秆菊', scientificName: 'Xerochrysum bracteatum', family: '菊科', origin: '澳大利亚', difficulty: 2, tags: ['观花'] },
  { category: 'flowering', name: '勋章菊', scientificName: 'Gazania rigens', family: '菊科', origin: '南非', difficulty: 2, tags: ['观花'] },
  { category: 'flowering', name: '非洲菊', scientificName: 'Gerbera jamesonii', family: '菊科', origin: '南非', difficulty: 2, tags: ['观花'] },
  { category: 'flowering', name: '扶郎花', scientificName: 'Gerbera', family: '菊科', origin: '南非', difficulty: 2, tags: ['观花'] },
  { category: 'flowering', name: '金盏菊', scientificName: 'Calendula officinalis', family: '菊科', origin: '地中海', difficulty: 1, tags: ['观花', '新手友好'] },
  { category: 'flowering', name: '孔雀草', scientificName: 'Tagetes patula', family: '菊科', origin: '墨西哥', difficulty: 1, tags: ['观花', '新手友好'] },
  { category: 'flowering', name: '万寿菊', scientificName: 'Tagetes erecta', family: '菊科', origin: '墨西哥', difficulty: 1, tags: ['观花', '新手友好'] },
  { category: 'flowering', name: '百日草', scientificName: 'Zinnia elegans', family: '菊科', origin: '墨西哥', difficulty: 1, tags: ['观花', '新手友好'] },
  { category: 'flowering', name: '蛇目菊', scientificName: 'Sanvitalia procumbens', family: '菊科', origin: '墨西哥', difficulty: 1, tags: ['观花', '新手友好'] },
  { category: 'flowering', name: '波斯菊', scientificName: 'Cosmos bipinnatus', family: '菊科', origin: '墨西哥', difficulty: 1, tags: ['观花', '新手友好'] },
  { category: 'flowering', name: '硫华菊', scientificName: 'Cosmos sulphureus', family: '菊科', origin: '墨西哥', difficulty: 1, tags: ['观花', '新手友好'] },
  { category: 'flowering', name: '格桑花', scientificName: 'Cosmos', family: '菊科', origin: '西藏', difficulty: 1, tags: ['观花', '新手友好'] },
  { category: 'flowering', name: '向日葵', scientificName: 'Helianthus annuus', family: '菊科', origin: '北美', difficulty: 1, tags: ['观花', '新手友好'] },
  { category: 'flowering', name: '小向日葵', scientificName: 'Helianthus annuus Small', family: '菊科', origin: '北美', difficulty: 1, tags: ['观花', '新手友好'] },
  { category: 'flowering', name: '观赏向日葵', scientificName: 'Helianthus', family: '菊科', origin: '北美', difficulty: 1, tags: ['观花', '新手友好'] },
  { category: 'flowering', name: '大丽花', scientificName: 'Dahlia pinnata', family: '菊科', origin: '墨西哥', difficulty: 3, tags: ['观花', '球根'] },
  { category: 'flowering', name: '小丽花', scientificName: 'Dahlia pinnata Small', family: '菊科', origin: '墨西哥', difficulty: 3, tags: ['观花', '球根'] },
  { category: 'flowering', name: '大理花', scientificName: 'Dahlia', family: '菊科', origin: '墨西哥', difficulty: 3, tags: ['观花', '球根'] },
  { category: 'flowering', name: '美人蕉', scientificName: 'Canna indica', family: '美人蕉科', origin: '印度', difficulty: 2, tags: ['观花'] },
  { category: 'flowering', name: '姜花', scientificName: 'Hedychium coronarium', family: '姜科', origin: '亚洲', difficulty: 2, tags: ['观花', '芳香'] },
  { category: 'flowering', name: '荷花', scientificName: 'Nelumbo nucifera', family: '莲科', origin: '中国', difficulty: 3, tags: ['观花', '水生'] },
  { category: 'flowering', name: '睡莲', scientificName: 'Nymphaea', family: '睡莲科', origin: '全球', difficulty: 3, tags: ['观花', '水生'] },
  { category: 'flowering', name: '王莲', scientificName: 'Victoria amazonica', family: '睡莲科', origin: '南美洲', difficulty: 4, tags: ['观花', '水生', '大型'] },
  { category: 'flowering', name: '水仙', scientificName: 'Narcissus tazetta', family: '石蒜科', origin: '中国', difficulty: 2, tags: ['观花', '球根'] },
  { category: 'flowering', name: '洋水仙', scientificName: 'Narcissus', family: '石蒜科', origin: '欧洲', difficulty: 2, tags: ['观花', '球根'] },
  { category: 'flowering', name: '中国水仙', scientificName: 'Narcissus tazetta var. chinensis', family: '石蒜科', origin: '中国', difficulty: 2, tags: ['观花', '球根'] },
  { category: 'flowering', name: '朱顶红', scientificName: 'Hippeastrum rutilum', family: '石蒜科', origin: '南美洲', difficulty: 2, tags: ['观花', '球根'] },
  { category: 'flowering', name: '孤挺花', scientificName: 'Hippeastrum', family: '石蒜科', origin: '南美洲', difficulty: 2, tags: ['观花', '球根'] },
  { category: 'flowering', name: '文殊兰', scientificName: 'Crinum asiaticum', family: '石蒜科', origin: '亚洲', difficulty: 2, tags: ['观花'] },
  { category: 'flowering', name: '蜘蛛兰', scientificName: 'Hymenocallis', family: '石蒜科', origin: '美洲', difficulty: 2, tags: ['观花'] },
  { category: 'flowering', name: '网球花', scientificName: 'Haemanthus', family: '石蒜科', origin: '非洲', difficulty: 3, tags: ['观花', '球根'] },
  { category: 'flowering', name: '垂笑君子兰', scientificName: 'Clivia nobilis', family: '石蒜科', origin: '南非', difficulty: 3, tags: ['观花'] },
  { category: 'flowering', name: '细叶君子兰', scientificName: 'Clivia gardenii', family: '石蒜科', origin: '南非', difficulty: 3, tags: ['观花'] },
  { category: 'flowering', name: '黄花君子兰', scientificName: 'Clivia miniata citrina', family: '石蒜科', origin: '南非', difficulty: 3, tags: ['观花'] },
  { category: 'flowering', name: '白花君子兰', scientificName: 'Clivia miniata alba', family: '石蒜科', origin: '南非', difficulty: 3, tags: ['观花'] },
  { category: 'flowering', name: '缟花君子兰', scientificName: 'Clivia miniata variegata', family: '石蒜科', origin: '南非', difficulty: 3, tags: ['观花'] },
  { category: 'flowering', name: '短叶君子兰', scientificName: 'Clivia miniata Dwarf', family: '石蒜科', origin: '南非', difficulty: 3, tags: ['观花'] },
  { category: 'flowering', name: '长叶君子兰', scientificName: 'Clivia miniata Long', family: '石蒜科', origin: '南非', difficulty: 3, tags: ['观花'] },
  { category: 'flowering', name: '宽叶君子兰', scientificName: 'Clivia miniata Wide', family: '石蒜科', origin: '南非', difficulty: 3, tags: ['观花'] },
  { category: 'flowering', name: '窄叶君子兰', scientificName: 'Clivia miniata Narrow', family: '石蒜科', origin: '南非', difficulty: 3, tags: ['观花'] },
  { category: 'flowering', name: '花叶君子兰', scientificName: 'Clivia miniata Variegata', family: '石蒜科', origin: '南非', difficulty: 3, tags: ['观花'] },
  { category: 'flowering', name: '斑叶君子兰', scientificName: 'Clivia miniata Spotted', family: '石蒜科', origin: '南非', difficulty: 3, tags: ['观花'] },
  { category: 'flowering', name: '金边君子兰', scientificName: 'Clivia miniata Golden', family: '石蒜科', origin: '南非', difficulty: 3, tags: ['观花'] },
  { category: 'flowering', name: '银边君子兰', scientificName: 'Clivia miniata Silver', family: '石蒜科', origin: '南非', difficulty: 3, tags: ['观花'] },
  
  // 香草植物
  { category: 'herb', name: '香茅', scientificName: 'Cymbopogon nardus', family: '禾本科', origin: '亚洲', difficulty: 2, tags: ['香草'] },
  { category: 'herb', name: '柠檬香蜂草', scientificName: 'Melissa officinalis', family: '唇形科', origin: '欧洲', difficulty: 2, tags: ['香草'] },
  { category: 'herb', name: '马郁兰', scientificName: 'Origanum majorana', family: '唇形科', origin: '地中海', difficulty: 2, tags: ['香草'] },
  { category: 'herb', name: '龙蒿', scientificName: 'Artemisia dracunculus', family: '菊科', origin: '欧洲', difficulty: 2, tags: ['香草'] },
  { category: 'herb', name: '香芹', scientificName: 'Petroselinum crispum', family: '伞形科', origin: '地中海', difficulty: 2, tags: ['香草'] },
  { category: 'herb', name: '琉璃苣', scientificName: 'Borago officinalis', family: '紫草科', origin: '地中海', difficulty: 1, tags: ['香草', '新手友好'] },
  { category: 'herb', name: '香叶天竺葵', scientificName: 'Pelargonium graveolens', family: '牻牛儿苗科', origin: '南非', difficulty: 2, tags: ['香草'] },
  { category: 'herb', name: '薄荷', scientificName: 'Mentha spicata', family: '唇形科', origin: '欧洲', difficulty: 1, tags: ['香草', '新手友好'] },
  { category: 'herb', name: '留兰香薄荷', scientificName: 'Mentha spicata', family: '唇形科', origin: '欧洲', difficulty: 1, tags: ['香草', '新手友好'] },
  { category: 'herb', name: '胡椒薄荷', scientificName: 'Mentha piperita', family: '唇形科', origin: '欧洲', difficulty: 1, tags: ['香草', '新手友好'] },
  { category: 'herb', name: '巧克力薄荷', scientificName: 'Mentha piperita Chocolate', family: '唇形科', origin: '欧洲', difficulty: 1, tags: ['香草', '新手友好'] },
  { category: 'herb', name: '苹果薄荷', scientificName: 'Mentha suaveolens', family: '唇形科', origin: '欧洲', difficulty: 1, tags: ['香草', '新手友好'] },
  { category: 'herb', name: '凤梨薄荷', scientificName: 'Mentha suaveolens Variegata', family: '唇形科', origin: '欧洲', difficulty: 1, tags: ['香草', '新手友好'] },
  { category: 'herb', name: '柠檬薄荷', scientificName: 'Mentha citrata', family: '唇形科', origin: '欧洲', difficulty: 1, tags: ['香草', '新手友好'] },
  { category: 'herb', name: '姜薄荷', scientificName: 'Mentha gracilis', family: '唇形科', origin: '欧洲', difficulty: 1, tags: ['香草', '新手友好'] },
  { category: 'herb', name: '橙薄荷', scientificName: 'Mentha citrata', family: '唇形科', origin: '欧洲', difficulty: 1, tags: ['香草', '新手友好'] },
  { category: 'herb', name: '葡萄柚薄荷', scientificName: 'Mentha piperita Grapefruit', family: '唇形科', origin: '欧洲', difficulty: 1, tags: ['香草', '新手友好'] },
  { category: 'herb', name: '草莓薄荷', scientificName: 'Mentha piperita Strawberry', family: '唇形科', origin: '欧洲', difficulty: 1, tags: ['香草', '新手友好'] },
  { category: 'herb', name: '香蕉薄荷', scientificName: 'Mentha piperita Banana', family: '唇形科', origin: '欧洲', difficulty: 1, tags: ['香草', '新手友好'] },
  { category: 'herb', name: '生姜薄荷', scientificName: 'Mentha piperita Ginger', family: '唇形科', origin: '欧洲', difficulty: 1, tags: ['香草', '新手友好'] },
  { category: 'herb', name: '薰衣草薄荷', scientificName: 'Mentha piperita Lavender', family: '唇形科', origin: '欧洲', difficulty: 1, tags: ['香草', '新手友好'] },
  { category: 'herb', name: '玫瑰薄荷', scientificName: 'Mentha piperita Rose', family: '唇形科', origin: '欧洲', difficulty: 1, tags: ['香草', '新手友好'] },
  { category: 'herb', name: '茉莉薄荷', scientificName: 'Mentha piperita Jasmine', family: '唇形科', origin: '欧洲', difficulty: 1, tags: ['香草', '新手友好'] },
  { category: 'herb', name: '柠檬罗勒', scientificName: 'Ocimum citriodorum', family: '唇形科', origin: '亚洲', difficulty: 2, tags: ['香草'] },
  { category: 'herb', name: '泰国罗勒', scientificName: 'Ocimum basilicum var. thyrsiflora', family: '唇形科', origin: '亚洲', difficulty: 2, tags: ['香草'] },
  { category: 'herb', name: '圣罗勒', scientificName: 'Ocimum tenuiflorum', family: '唇形科', origin: '印度', difficulty: 2, tags: ['香草'] },
  { category: 'herb', name: '肉桂罗勒', scientificName: 'Ocimum basilicum Cinnamon', family: '唇形科', origin: '亚洲', difficulty: 2, tags: ['香草'] },
  { category: 'herb', name: '紫罗勒', scientificName: 'Ocimum basilicum Purple', family: '唇形科', origin: '亚洲', difficulty: 2, tags: ['香草'] },
  { category: 'herb', name: '皱叶罗勒', scientificName: 'Ocimum basilicum Crispum', family: '唇形科', origin: '亚洲', difficulty: 2, tags: ['香草'] },
  { category: 'herb', name: '大叶罗勒', scientificName: 'Ocimum basilicum Large', family: '唇形科', origin: '亚洲', difficulty: 2, tags: ['香草'] },
  { category: 'herb', name: '小叶罗勒', scientificName: 'Ocimum basilicum Small', family: '唇形科', origin: '亚洲', difficulty: 2, tags: ['香草'] },
  { category: 'herb', name: '甜罗勒', scientificName: 'Ocimum basilicum Sweet', family: '唇形科', origin: '亚洲', difficulty: 2, tags: ['香草'] },
  { category: 'herb', name: '热那亚罗勒', scientificName: 'Ocimum basilicum Genovese', family: '唇形科', origin: '意大利', difficulty: 2, tags: ['香草'] },
  { category: 'herb', name: '希腊罗勒', scientificName: 'Ocimum basilicum Greek', family: '唇形科', origin: '希腊', difficulty: 2, tags: ['香草'] },
  { category: 'herb', name: '意大利罗勒', scientificName: 'Ocimum basilicum Italian', family: '唇形科', origin: '意大利', difficulty: 2, tags: ['香草'] },
  { category: 'herb', name: '法国罗勒', scientificName: 'Ocimum basilicum French', family: '唇形科', origin: '法国', difficulty: 2, tags: ['香草'] },
  { category: 'herb', name: '英国罗勒', scientificName: 'Ocimum basilicum English', family: '唇形科', origin: '英国', difficulty: 2, tags: ['香草'] },
  { category: 'herb', name: '美国罗勒', scientificName: 'Ocimum basilicum American', family: '唇形科', origin: '美国', difficulty: 2, tags: ['香草'] },
  { category: 'herb', name: '德国罗勒', scientificName: 'Ocimum basilicum German', family: '唇形科', origin: '德国', difficulty: 2, tags: ['香草'] },
  { category: 'herb', name: '西班牙罗勒', scientificName: 'Ocimum basilicum Spanish', family: '唇形科', origin: '西班牙', difficulty: 2, tags: ['香草'] },
  { category: 'herb', name: '葡萄牙罗勒', scientificName: 'Ocimum basilicum Portuguese', family: '唇形科', origin: '葡萄牙', difficulty: 2, tags: ['香草'] },
  { category: 'herb', name: '荷兰罗勒', scientificName: 'Ocimum basilicum Dutch', family: '唇形科', origin: '荷兰', difficulty: 2, tags: ['香草'] },
  { category: 'herb', name: '比利时罗勒', scientificName: 'Ocimum basilicum Belgian', family: '唇形科', origin: '比利时', difficulty: 2, tags: ['香草'] },
  { category: 'herb', name: '瑞士罗勒', scientificName: 'Ocimum basilicum Swiss', family: '唇形科', origin: '瑞士', difficulty: 2, tags: ['香草'] },
  { category: 'herb', name: '奥地利罗勒', scientificName: 'Ocimum basilicum Austrian', family: '唇形科', origin: '奥地利', difficulty: 2, tags: ['香草'] },
  { category: 'herb', name: '波兰罗勒', scientificName: 'Ocimum basilicum Polish', family: '唇形科', origin: '波兰', difficulty: 2, tags: ['香草'] },
  { category: 'herb', name: '捷克罗勒', scientificName: 'Ocimum basilicum Czech', family: '唇形科', origin: '捷克', difficulty: 2, tags: ['香草'] },
  { category: 'herb', name: '匈牙利罗勒', scientificName: 'Ocimum basilicum Hungarian', family: '唇形科', origin: '匈牙利', difficulty: 2, tags: ['香草'] },
  { category: 'herb', name: '罗马尼亚罗勒', scientificName: 'Ocimum basilicum Romanian', family: '唇形科', origin: '罗马尼亚', difficulty: 2, tags: ['香草'] },
  { category: 'herb', name: '保加利亚罗勒', scientificName: 'Ocimum basilicum Bulgarian', family: '唇形科', origin: '保加利亚', difficulty: 2, tags: ['香草'] },
  
  // 蕨类植物
  { category: 'fern', name: '翠云草', scientificName: 'Selaginella uncinata', family: '卷柏科', origin: '中国', difficulty: 3, tags: ['蕨类'] },
  { category: 'fern', name: '凤尾蕨', scientificName: 'Pteris cretica', family: '凤尾蕨科', origin: '全球', difficulty: 2, tags: ['蕨类'] },
  { category: 'fern', name: '蜈蚣草', scientificName: 'Pteris vittata', family: '凤尾蕨科', origin: '热带', difficulty: 2, tags: ['蕨类'] },
  { category: 'fern', name: '金毛狗蕨', scientificName: 'Cibotium barometz', family: '蚌壳蕨科', origin: '中国', difficulty: 3, tags: ['蕨类', '大型'] },
  { category: 'fern', name: '星蕨', scientificName: 'Microsorum punctatum', family: '水龙骨科', origin: '热带', difficulty: 2, tags: ['蕨类'] },
  { category: 'fern', name: '石韦', scientificName: 'Pyrrosia lingua', family: '水龙骨科', origin: '中国', difficulty: 2, tags: ['蕨类'] },
  { category: 'fern', name: '瓦韦', scientificName: 'Lepisorus thunbergianus', family: '水龙骨科', origin: '亚洲', difficulty: 2, tags: ['蕨类'] },
  { category: 'fern', name: '连珠蕨', scientificName: 'Aglaomorpha', family: '水龙骨科', origin: '热带', difficulty: 3, tags: ['蕨类'] },
  { category: 'fern', name: '槲蕨', scientificName: 'Drynaria roosii', family: '槲蕨科', origin: '亚洲', difficulty: 2, tags: ['蕨类'] },
  { category: 'fern', name: '崖姜蕨', scientificName: 'Pseudodrynaria coronans', family: '水龙骨科', origin: '亚洲', difficulty: 2, tags: ['蕨类'] },
  { category: 'fern', name: '骨碎补', scientificName: 'Davallia mariesii', family: '骨碎补科', origin: '中国', difficulty: 2, tags: ['蕨类'] },
  { category: 'fern', name: '兔脚蕨', scientificName: 'Davallia fejeensis', family: '骨碎补科', origin: '斐济', difficulty: 2, tags: ['蕨类'] },
  { category: 'fern', name: '银蕨', scientificName: 'Cyathea dealbata', family: '桫椤科', origin: '新西兰', difficulty: 3, tags: ['蕨类', '大型'] },
  { category: 'fern', name: '桫椤', scientificName: 'Cyathea spinulosa', family: '桫椤科', origin: '中国', difficulty: 3, tags: ['蕨类', '大型', '稀有'] },
  { category: 'fern', name: '树蕨', scientificName: 'Dicksonia antarctica', family: '蚌壳蕨科', origin: '澳大利亚', difficulty: 3, tags: ['蕨类', '大型'] },
  { category: 'fern', name: '观音座莲', scientificName: 'Angiopteris evecta', family: '观音座莲科', origin: '亚洲', difficulty: 3, tags: ['蕨类', '大型'] },
  { category: 'fern', name: '福建观音座莲', scientificName: 'Angiopteris fokiensis', family: '观音座莲科', origin: '中国', difficulty: 3, tags: ['蕨类', '大型'] },
  { category: 'fern', name: '海金沙', scientificName: 'Lygodium japonicum', family: '海金沙科', origin: '亚洲', difficulty: 2, tags: ['蕨类', '爬藤'] },
  { category: 'fern', name: '蔓生海金沙', scientificName: 'Lygodium microphyllum', family: '海金沙科', origin: '热带', difficulty: 2, tags: ['蕨类', '爬藤'] },
  { category: 'fern', name: '铁线蕨', scientificName: 'Adiantum capillus-veneris', family: '铁线蕨科', origin: '全球', difficulty: 3, tags: ['蕨类'] },
  { category: 'fern', name: '扇叶铁线蕨', scientificName: 'Adiantum flabellulatum', family: '铁线蕨科', origin: '亚洲', difficulty: 3, tags: ['蕨类'] },
  { category: 'fern', name: '楔叶铁线蕨', scientificName: 'Adiantum cuneatum', family: '铁线蕨科', origin: '巴西', difficulty: 3, tags: ['蕨类'] },
  { category: 'fern', name: '月芽铁线蕨', scientificName: 'Adiantum lunulatum', family: '铁线蕨科', origin: '亚洲', difficulty: 3, tags: ['蕨类'] },
  { category: 'fern', name: '普通铁线蕨', scientificName: 'Adiantum pedatum', family: '铁线蕨科', origin: '北美', difficulty: 3, tags: ['蕨类'] },
  { category: 'fern', name: '阿拉斯加铁线蕨', scientificName: 'Adiantum aleuticum', family: '铁线蕨科', origin: '北美', difficulty: 3, tags: ['蕨类'] },
  { category: 'fern', name: '细叶铁线蕨', scientificName: 'Adiantum raddianum', family: '铁线蕨科', origin: '热带', difficulty: 3, tags: ['蕨类'] },
  { category: 'fern', name: ' Fragrans 铁线蕨', scientificName: 'Adiantum fragrans', family: '铁线蕨科', origin: '喜马拉雅', difficulty: 3, tags: ['蕨类'] },
  { category: 'fern', name: '美丽铁线蕨', scientificName: 'Adiantum formosum', family: '铁线蕨科', origin: '澳大利亚', difficulty: 3, tags: ['蕨类'] },
  { category: 'fern', name: '华丽铁线蕨', scientificName: 'Adiantum speciosum', family: '铁线蕨科', origin: '太平洋岛屿', difficulty: 3, tags: ['蕨类'] },
  { category: 'fern', name: '肾形铁线蕨', scientificName: 'Adiantum reniforme', family: '铁线蕨科', origin: '非洲', difficulty: 3, tags: ['蕨类'] },
  { category: 'fern', name: '圆形铁线蕨', scientificName: 'Adiantum rotundifolium', family: '铁线蕨科', origin: '非洲', difficulty: 3, tags: ['蕨类'] },
  { category: 'fern', name: '心形铁线蕨', scientificName: 'Adiantum cordatum', family: '铁线蕨科', origin: '非洲', difficulty: 3, tags: ['蕨类'] },
  { category: 'fern', name: '箭头铁线蕨', scientificName: 'Adiantum sagittatum', family: '铁线蕨科', origin: '南美洲', difficulty: 3, tags: ['蕨类'] },
  { category: 'fern', name: '长叶铁线蕨', scientificName: 'Adiantum elongatum', family: '铁线蕨科', origin: '南美洲', difficulty: 3, tags: ['蕨类'] },
  { category: 'fern', name: '短叶铁线蕨', scientificName: 'Adiantum brevifolium', family: '铁线蕨科', origin: '南美洲', difficulty: 3, tags: ['蕨类'] },
  { category: 'fern', name: '宽叶铁线蕨', scientificName: 'Adiantum latifolium', family: '铁线蕨科', origin: '南美洲', difficulty: 3, tags: ['蕨类'] },
  { category: 'fern', name: '窄叶铁线蕨', scientificName: 'Adiantum angustifolium', family: '铁线蕨科', origin: '南美洲', difficulty: 3, tags: ['蕨类'] },
  { category: 'fern', name: '大叶铁线蕨', scientificName: 'Adiantum macrophyllum', family: '铁线蕨科', origin: '南美洲', difficulty: 3, tags: ['蕨类'] },
  { category: 'fern', name: '小叶铁线蕨', scientificName: 'Adiantum microphyllum', family: '铁线蕨科', origin: '南美洲', difficulty: 3, tags: ['蕨类'] },
  { category: 'fern', name: '全缘铁线蕨', scientificName: 'Adiantum integrifolium', family: '铁线蕨科', origin: '印度', difficulty: 3, tags: ['蕨类'] },
  { category: 'fern', name: '锯齿铁线蕨', scientificName: 'Adiantum serratum', family: '铁线蕨科', origin: '南美洲', difficulty: 3, tags: ['蕨类'] },
  { category: 'fern', name: '波缘铁线蕨', scientificName: 'Adiantum undulatum', family: '铁线蕨科', origin: '南美洲', difficulty: 3, tags: ['蕨类'] },
  { category: 'fern', name: '卷缘铁线蕨', scientificName: 'Adiantum crispum', family: '铁线蕨科', origin: '太平洋岛屿', difficulty: 3, tags: ['蕨类'] },
  { category: 'fern', name: '皱叶铁线蕨', scientificName: 'Adiantum sinuosum', family: '铁线蕨科', origin: '新西兰', difficulty: 3, tags: ['蕨类'] },
  { category: 'fern', name: '光滑铁线蕨', scientificName: 'Adiantum glabrum', family: '铁线蕨科', origin: '南美洲', difficulty: 3, tags: ['蕨类'] },
  { category: 'fern', name: '毛轴铁线蕨', scientificName: 'Adiantum hispidulum', family: '铁线蕨科', origin: '澳大利亚', difficulty: 3, tags: ['蕨类'] },
  { category: 'fern', name: '无毛铁线蕨', scientificName: 'Adiantum glabratum', family: '铁线蕨科', origin: '南美洲', difficulty: 3, tags: ['蕨类'] },
  { category: 'fern', name: '有毛铁线蕨', scientificName: 'Adiantum villosum', family: '铁线蕨科', origin: '南美洲', difficulty: 3, tags: ['蕨类'] },
  { category: 'fern', name: '多毛铁线蕨', scientificName: 'Adiantum pilosum', family: '铁线蕨科', origin: '南美洲', difficulty: 3, tags: ['蕨类'] },
  { category: 'fern', name: '少毛铁线蕨', scientificName: 'Adiantum subglabrum', family: '铁线蕨科', origin: '南美洲', difficulty: 3, tags: ['蕨类'] },
  
  // 仙人掌
  { category: 'cactus', name: '光山', scientificName: 'Leucostele', family: '仙人掌科', origin: '南美洲', difficulty: 3, tags: ['仙人掌'] },
  { category: 'cactus', name: '龙神木', scientificName: 'Myrtillocactus geometrizans', family: '仙人掌科', origin: '墨西哥', difficulty: 2, tags: ['仙人掌'] },
  { category: 'cactus', name: '古代稀', scientificName: 'Bergerocactus', family: '仙人掌科', origin: '墨西哥', difficulty: 2, tags: ['仙人掌'] },
  { category: 'cactus', name: '将军', scientificName: 'Astrophytum', family: '仙人掌科', origin: '墨西哥', difficulty: 3, tags: ['仙人掌'] },
  { category: 'cactus', name: '帝冠', scientificName: 'Obregonia denegrii', family: '仙人掌科', origin: '墨西哥', difficulty: 4, tags: ['仙人掌', '稀有'] },
  { category: 'cactus', name: '白斜子', scientificName: 'Mammillaria', family: '仙人掌科', origin: '墨西哥', difficulty: 2, tags: ['仙人掌'] },
  { category: 'cactus', name: '松岚', scientificName: 'Cereus', family: '仙人掌科', origin: '南美洲', difficulty: 2, tags: ['仙人掌'] },
  { category: 'cactus', name: '彩云', scientificName: 'Gymnocalycium', family: '仙人掌科', origin: '南美洲', difficulty: 3, tags: ['仙人掌'] },
  { category: 'cactus', name: '牡丹玉', scientificName: 'Gymnocalycium', family: '仙人掌科', origin: '阿根廷', difficulty: 2, tags: ['仙人掌'] },
  { category: 'cactus', name: '多棱球', scientificName: 'Echinocactus', family: '仙人掌科', origin: '墨西哥', difficulty: 2, tags: ['仙人掌'] },
  { category: 'cactus', name: '英冠玉', scientificName: 'Notocactus leninghausii', family: '仙人掌科', origin: '巴西', difficulty: 2, tags: ['仙人掌'] },
  { category: 'cactus', name: